// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rorhrebdmvdxzhvdvldr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvcmhyZWJkbXZkeHpodmR2bGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjAwMzEsImV4cCI6MjA2NTQ5NjAzMX0.iNU19MPIuxEveRcyZcsS1yc8spPEdZYU02bZh8MQS5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);